#General Data
name: Reserve
version: 0.1.0.10
description: A set of APIs for unison across Bukkit Plugins.
author: creatorfromhell

#Plugin Data
main: net.tnemc.core.Reserve
load: startup
softdepend: [Vault]