#General Data
name: Reserve
version: 0.1.0.8
description: An economy API for unison across Bukkit Plugins.
author: creatorfromhell

#Plugin Data
main: net.tnemc.core.Reserve
load: startup
softdepend: [Vault]